package com.androiddevs.mvvmnewsapp

import androidx.room.Entity
import androidx.room.PrimaryKey

//denotes that it is a table in room db
@Entity(tableName = "articles")
data class Article(
    @PrimaryKey(autoGenerate = true)
    var id: Int? = null,
    //primary key denotes this to be primary key in table in room db
    //it is autogenerated by room db
    //id is declared as nullable as id is  being alloted to only those articles that are stored or saved in room db
    // there might be some articles that are directly shown without storing in db
    val author: String,
    val content: String,
    val description: String,
    val publishedAt: String,
    val source: Source,
    val title: String,
    val url: String,
    val urlToImage: String
)